### ISSUE TITLE
Integrate the creation and use of conda-pack'd envs with dynamically generate --conda-yml envs for quicker restarts

### ISSUE THREAD

**Issue by mkandes** [mkandes/galyleo#11]

**Comment by pwrose** [comment]
Here is a suggestion about caching the conda-pack environment.

1. Add a "--cache" option
2. When a new conda env is first specified, e.g.
`galyleo options  --conda-env <env_name> --conda-yml <env_yml> --cache`, a packed conda environment is stored, e.g in ${HOME}/.galyleo-cache/<env_name>/<env_name>.tar.gz.  Also, the `<env_yml>` file is stored in this directory.
3. When the same command line is run again, the specified `env_yml` file is checked against the cached `env_yml` file. If they are identical, then the cached conda environment is used, otherwise, a new packed conda environment is created.
4. We may also want to cache the /Miniconda3-latest-Linux-x86_64.sh file.

The cache directory may look like this:
```
${HOME}/.galyleo-cache
    Miniconda3-latest-Linux-x86_64.sh
    notebooks-sharing
            notebooks-sharing.tar.gz
            notebooks-sharing.yml
    next-environment-here

I've tried to create a simple bash script to show the logic. It isn't working, but it gives you an idea. On Expanse see pwrose/galyleo-cache.sb.

**Comment by mkandes** [comment]
@pwrose - Done. But I have not yet deployed the update to Expanse yet. I will do so sometime next week and let you know, if you're interested in testing this new feature. I'd like to make a good pass through and clean up the README.md documentation before pushing the new version into production.

https://github.com/mkandes/galyleo/commit/f9decd05526af78022501479a8054941c3b2170a
